class CountryCodes {
  static Map currencyCode = {
    "AFN": {"country_code": "AF", "country_name": "Afghanistan"},
    "ALL": {"country_code": "AL", "country_name": "Albania"},
    "DZD": {"country_code": "DZ", "country_name": "Algeria"},
    "EUR": {"country_code": "BE", "country_name": "Belgium"},
    "AOA": {"country_code": "AO", "country_name": "Angola"},
    "ARS": {"country_code": "AR", "country_name": "Argentina"},
    "AMD": {"country_code": "AM", "country_name": "Armenia"},
    "AUD": {"country_code": "AU", "country_name": "Australia"},
    "AZN": {"country_code": "AZ", "country_name": "Azerbaijan"},
    "BSD": {"country_code": "BS", "country_name": "Bahamas"},
    "BHD": {"country_code": "BH", "country_name": "Bahrain"},
    "BDT": {"country_code": "BD", "country_name": "Bangladesh"},
    "BYN": {"country_code": "BY", "country_name": "Belarus"},
    "BZD": {"country_code": "BZ", "country_name": "Belize"},
    "XOF": {"country_code": "BF", "country_name": "Burkina Faso"},
    "BTN": {"country_code": "BT", "country_name": "Bhutan"},
    "BOB": {"country_code": "BO", "country_name": "Bolivia"},
    "BAM": {"country_code": "BA", "country_name": "Bosnia and Herzegovina"},
    "BWP": {"country_code": "BW", "country_name": "Botswana"},
    "BRL": {"country_code": "BR", "country_name": "Brazil"},
    "BND": {"country_code": "BN", "country_name": "Brunei"},
    "BGN": {"country_code": "BG", "country_name": "Bulgaria"},
    "BIF": {"country_code": "BI", "country_name": "Burundi"},
    "KHR": {"country_code": "KH", "country_name": "Cambodia"},
    "XAF": {"country_code": "CM", "country_name": "Cameroon"},
    "CAD": {"country_code": "CA", "country_name": "Canada"},
    "CVE": {"country_code": "CV", "country_name": "Cape Verde"},
    "CLP": {"country_code": "CL", "country_name": "Chile"},
    "CNY": {"country_code": "CN", "country_name": "China"},
    "COP": {"country_code": "CO", "country_name": "Colombia"},
    "KMF": {"country_code": "KM", "country_name": "Comoros"},
    "CDF": {"country_code": "CD", "country_name": "Congo"},
    "CRC": {"country_code": "CR", "country_name": "Costa Rica"},
    "HRK": {"country_code": "HR", "country_name": "Croatia"},
    "CUP": {"country_code": "CU", "country_name": "Cuba"},
    "CZK": {"country_code": "CZ", "country_name": "Czech Republic"},
    "DKK": {"country_code": "DK", "country_name": "Denmark"},
    "DJF": {"country_code": "DJ", "country_name": "Djibouti"},
    "XCD": {"country_code": "DM", "country_name": "Dominica"},
    "DOP": {"country_code": "DO", "country_name": "Dominican Republic"},
    "USD": {"country_code": "US", "country_name": "United States"},
    "EGP": {"country_code": "EG", "country_name": "Egypt"},
    "ERN": {"country_code": "ER", "country_name": "Eritrea"},
    "ETB": {"country_code": "ET", "country_name": "Ethiopia"},
    "FJD": {"country_code": "FJ", "country_name": "Fiji"},
    "GMD": {"country_code": "GM", "country_name": "Gambia"},
    "GEL": {"country_code": "GE", "country_name": "Georgia"},
    "GHS": {"country_code": "GH", "country_name": "Ghana"},
    "GTQ": {"country_code": "GT", "country_name": "Guatemala"},
    "GNF": {"country_code": "GN", "country_name": "Guinea"},
    "GYD": {"country_code": "GY", "country_name": "Guyana"},
    "HTG": {"country_code": "HT", "country_name": "Haiti"},
    "HNL": {"country_code": "HN", "country_name": "Honduras"},
    "HUF": {"country_code": "HU", "country_name": "Hungary"},
    "ISK": {"country_code": "IS", "country_name": "Iceland"},
    "INR": {"country_code": "IN", "country_name": "India"},
    "IDR": {"country_code": "ID", "country_name": "Indonesia"},
    "IRR": {"country_code": "IR", "country_name": "Iran"},
    "IQD": {"country_code": "IQ", "country_name": "Iraq"},
    "ILS": {"country_code": "IL", "country_name": "Israel"},
    "JMD": {"country_code": "JM", "country_name": "Jamaica"},
    "JPY": {"country_code": "JP", "country_name": "Japan"},
    "JOD": {"country_code": "JO", "country_name": "Jordan"},
    "KZT": {"country_code": "KZ", "country_name": "Kazakhstan"},
    "KES": {"country_code": "KE", "country_name": "Kenya"},
    "KPW": {"country_code": "KP", "country_name": "North Korea"},
    "KRW": {"country_code": "KR", "country_name": "South Korea"},
    "KWD": {"country_code": "KW", "country_name": "Kuwait"},
    "KGS": {"country_code": "KG", "country_name": "Kyrgyzstan"},
    "LAK": {"country_code": "LA", "country_name": "Laos"},
    "LBP": {"country_code": "LB", "country_name": "Lebanon"},
    "LSL": {"country_code": "LS", "country_name": "Lesotho"},
    "LRD": {"country_code": "LR", "country_name": "Liberia"},
    "LYD": {"country_code": "LY", "country_name": "Libya"},
    "CHF": {"country_code": "CH", "country_name": "Switzerland"},
    "MGA": {"country_code": "MG", "country_name": "Madagascar"},
    "MWK": {"country_code": "MW", "country_name": "Malawi"},
    "MYR": {"country_code": "MY", "country_name": "Malaysia"},
    "MVR": {"country_code": "MV", "country_name": "Maldives"},
    "MRU": {"country_code": "MR", "country_name": "Mauritania"},
    "MUR": {"country_code": "MU", "country_name": "Mauritius"},
    "MXN": {"country_code": "MX", "country_name": "Mexico"},
    "MDL": {"country_code": "MD", "country_name": "Moldova"},
    "MNT": {"country_code": "MN", "country_name": "Mongolia"},
    "MAD": {"country_code": "MA", "country_name": "Morocco"},
    "MZN": {"country_code": "MZ", "country_name": "Mozambique"},
    "MMK": {"country_code": "MM", "country_name": "Myanmar"},
    "NAD": {"country_code": "NA", "country_name": "Namibia"},
    "NPR": {"country_code": "NP", "country_name": "Nepal"},
    "ANG": {"country_code": "NL", "country_name": "Netherlands"},
    "NZD": {"country_code": "NZ", "country_name": "New Zealand"},
    "NIO": {"country_code": "NI", "country_name": "Nicaragua"},
    "NGN": {"country_code": "NG", "country_name": "Nigeria"},
    "NOK": {"country_code": "NO", "country_name": "Norway"},
    "OMR": {"country_code": "OM", "country_name": "Oman"},
    "PKR": {"country_code": "PK", "country_name": "Pakistan"},
    "PAB": {"country_code": "PA", "country_name": "Panama"},
    "PGK": {"country_code": "PG", "country_name": "Papua New Guinea"},
    "PYG": {"country_code": "PY", "country_name": "Paraguay"},
    "PEN": {"country_code": "PE", "country_name": "Peru"},
    "PHP": {"country_code": "PH", "country_name": "Philippines"},
    "PLN": {"country_code": "PL", "country_name": "Poland"},
    "QAR": {"country_code": "QA", "country_name": "Qatar"},
    "RON": {"country_code": "RO", "country_name": "Romania"},
    "RUB": {"country_code": "RU", "country_name": "Russia"},
    "RWF": {"country_code": "RW", "country_name": "Rwanda"},
    "SHP": {"country_code": "SH", "country_name": "Saint Helena"},
    "WST": {"country_code": "WS", "country_name": "Samoa"},
    "STN": {"country_code": "ST", "country_name": "Sao Tome and Principe"},
    "SAR": {"country_code": "SA", "country_name": "Saudi Arabia"},
    "RSD": {"country_code": "RS", "country_name": "Serbia"},
    "SCR": {"country_code": "SC", "country_name": "Seychelles"},
    "SLL": {"country_code": "SL", "country_name": "Sierra Leone"},
    "SGD": {"country_code": "SG", "country_name": "Singapore"},
    "SBD": {"country_code": "SB", "country_name": "Solomon Islands"},
    "SOS": {"country_code": "SO", "country_name": "Somalia"},
    "ZAR": {"country_code": "ZA", "country_name": "South Africa"},
    "LKR": {"country_code": "LK", "country_name": "Sri Lanka"},
    "SDG": {"country_code": "SD", "country_name": "Sudan"},
    "SRD": {"country_code": "SR", "country_name": "Suriname"},
    "SZL": {"country_code": "SZ", "country_name": "Eswatini"},
    "SEK": {"country_code": "SE", "country_name": "Sweden"},
    "SYP": {"country_code": "SY", "country_name": "Syria"},
    "TWD": {"country_code": "TW", "country_name": "Taiwan"},
    "TJS": {"country_code": "TJ", "country_name": "Tajikistan"},
    "TZS": {"country_code": "TZ", "country_name": "Tanzania"},
    "THB": {"country_code": "TH", "country_name": "Thailand"},
    "TOP": {"country_code": "TO", "country_name": "Tonga"},
    "TTD": {"country_code": "TT", "country_name": "Trinidad and Tobago"},
    "TND": {"country_code": "TN", "country_name": "Tunisia"},
    "TRY": {"country_code": "TR", "country_name": "Turkey"},
    "TMT": {"country_code": "TM", "country_name": "Turkmenistan"},
    "UGX": {"country_code": "UG", "country_name": "Uganda"},
    "UAH": {"country_code": "UA", "country_name": "Ukraine"},
    "AED": {"country_code": "AE", "country_name": "United Arab Emirates"},
    "GBP": {"country_code": "GB", "country_name": "United Kingdom"},
    "UYU": {"country_code": "UY", "country_name": "Uruguay"},
    "UZS": {"country_code": "UZ", "country_name": "Uzbekistan"},
    "VUV": {"country_code": "VU", "country_name": "Vanuatu"},
    "VES": {"country_code": "VE", "country_name": "Venezuela"},
    "VND": {"country_code": "VN", "country_name": "Vietnam"},
    "YER": {"country_code": "YE", "country_name": "Yemen"},
    "ZMW": {"country_code": "ZM", "country_name": "Zambia"},
    "ZWL": {"country_code": "ZW", "country_name": "Zimbabwe"},
  };
}
